sonar.projectKey=app-finops_myproject
sonar.organization=app-finops
sonar.sources=.

# Target all source folders and standalone Python/JS files
sonar.inclusions=backend/**,frontend/**,database/**,ravi.py,cherrypick.py,vunlerableapp.js,vunlerableapp.py,vulnerableapp.js,vulnerableapp.py

# Exclusions
sonar.exclusions=**/node_modules/**,**/.github/**,**/__pycache__/**,**/*.pyc,**/*.md,deploy.sh,setup-ec2.sh,**/Dockerfile

# Encoding and Language configurations
sonar.sourceEncoding=UTF-8
sonar.python.version=3
sonar.javascript.file.suffixes=.js,.jsx

# Duplication (CPD) sensitivity thresholds
sonar.cpd.python.minimumLines=10
sonar.cpd.python.minimumTokens=20
sonar.cpd.javascript.minimumLines=10
sonar.cpd.javascript.minimumTokens=20
